CREATE USER airbnbp 
IDENTIFIED BY airbnbp
DEFAULT TABLESPACE SYSTEM
TEMPORARY TABLESPACE TEMP
QUOTA 10M ON SYSTEM;

GRANT create session, create table, create sequence,create view
to airbnb;

ALTER USER airbnb
IDENTIFIED BY 12345678;

GRANT CREATE SESSION TO airbnbP;

GRANT ALL PRIVILEGES TO airbnbp;

select * from ;

GRANT SELECT ON SYS.CITY TO airbnbp ;
GRANT SELECT ON SYS.REVIEW TO airbnbp;
GRANT SELECT ON SYS.PLACE TO airbnbp;
GRANT SELECT ON SYS.USUARIO TO airbnbp;
GRANT SELECT ON SYS.STATES TO airbnbp;
GRANT SELECT ON SYS.AMENITY TO airbnbp;
GRANT SELECT ON SYS.PLACEAMENITY TO airbnbp;